language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- "wget -O ./_data/news.csv $(bundle exec yaml get news-feed -F=_config.yml) || :"
- "wget -O ./_data/events.csv $(bundle exec yaml get events-feed -F=_config.yml) || :"
- "wget -O ./_data/profiles.csv $(bundle exec yaml get faculty-feed -F=_config.yml) || :"
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: QmQJ3BygvJYnKiKE34hMkJaY7ajKy2YRp7B3h7mD6Ik+WfaqfsW/GdMTB6RhLVRRgCWtbWN4MJ15QKIBHSO9E9R4wTE6vLFU6mwSk7nCNKRcD1vuqC9uEZXEh6niyw37sguLL6v0SQPGgpWcYC1/yWm/2GO+8oAFvCb/hl+F7jIP8YNIbFdKjLFQ0krha4mP0rVTUQOVUVlBW6heh5N8LOO0aOl7XoiAdCvKvKOYS8H65fYp3JY/tL4kJe/HnmSXShZjVJexBXYOpw3UHaodJFOGAtdEtsMz4OUt+jwvzBvgUkRHVGmqR/OilFB9p7c1ybtQIWsSSm106kN9F1uESyMC82KqWLxhns4ZqVGKFa0SFQT7naQ4UdJlLQYLT06pxqGuLF4eL99biR0fRIWkK/ZvENO0VZd7uNyBs+fO7gPSmGZGijbNvKIKKr9aR2qlBZEyavaP+JTheaTJhizhw7+RNijYV2PgE82vLmDjXap8+XccxvDqqvnc4e6p6UZ+SiZCLvNMj/4/GmfqukrkaakFhiRwrcsv1PItHuM+hKfH01/4+ScwZmzVOSDHenmjL+Qpkk0j5i/cgfW9dJIT92FWhfSlc4y4ZOGf4B2v5YRfb7Thx2B0/6L/w9sWw+gjNyNKxlj6wQud5HEOOhYqSIHre3y712+/dyBa0Y/O5XE=
    on_success: always
